export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID"
export const GET_COUNTRY_BY_NAME =  "GET_COUNTRY_BY_NAME"
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES"
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT"
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY"
export const ORDER_POPULATION = "ORDER_POPULATION"
export const ORDER_ALPHABETICAL = "ORDER_ALPHABETICAL"


